### PR TITLE
changed variables definition to final

### PR DESCRIPTION
**Pull request by jaykay99992**
I added the final to variable definitions to ensure that they cannot be changed after being assigned

### CODE REVIEW

**Review by ram229kumar — COMMENTED** [review]
Making the variables final prevents it from being modified and since the values are assigned via constructor they won't be changed anymore. Looks good.

**Comment by jaykay99992** [comment]
@ram229kumar Sure I will also merge this one too in a bit, if you feel that i shouldn't please let me know.

**Comment by ram229kumar** [comment]
@jaykay99992 looks good you can merge it. Thanks

**Comment by jaykay9999** [comment]
Sure, code merged

**Pull request merged**
