### PR TITLE
removed unused large code comments

### PR DESCRIPTION
**Pull request by jaykay99992**
A large unused code comment of what seems to be like an old code, is removed for clarity.

### CODE REVIEW

**Review by ram229kumar — COMMENTED** [review]
Removing the unused code helps improve readability and also helps developers to avoid confusion in future as whether its needed or safe to remove. Looks good.

**Comment by jaykay99992** [comment]
@ram229kumar Sure, I will proceed to merge it shortly, If you have any objections, please let me know.

**Comment by ram229kumar** [comment]
Looks good you can merge it. Thanks

**Comment by jaykay9999** [comment]
Code approved and merged

**Pull request merged**
