### PR TITLE
application start up code changes

### PR DESCRIPTION
**Pull request by jaykay99992**
I changed the function startsWith() to contain() , in case the os name does not start with exactly the key words "win" or "mac" .

I also removed the if "win" condition because the windows application will launch either way if the os name does not match the conditions

### CODE REVIEW

**Comment by anuja-kulkarni** [comment]
Lgtm, can you please make sure to test this before merging?

**Review by anuja-kulkarni — APPROVED** [review]

**Comment by jaykay99992** [comment]
@anuja-kulkarni tested this with my windows machine and works fine. As for mac the operating system name does contain the string "mac" which indeed will work the same as the previous code. Do i proceed to merge ?

**Comment by anuja-kulkarni** [comment]
Sounds good. Yes, the changes can be merged.

**Comment by jaykay9999** [comment]
Code approved and merged

**Pull request merged**
