### PR TITLE
reduced comments and changed variable names for method grow

### PR DESCRIPTION
**Pull request by jaykay99992**
The comment for method grow() was too lengthy so I reduced it. And I changed the variable names v and h to VE and HE to give a clearer abbreviation

### CODE REVIEW

**Comment by nrf-um** [comment]
The original comments were a muddled mess of HTML tags and prose which made it hard to decipher what exactly the comments were describing. The updated comments have removed that issue by removing all HTML tags other than the paragraph tag at the start of the comment. Looking at the rest of the code in the file, the paragraph tag could be removed as well but it does not truly hamper the readability if it stays.

Some of the original comments were longer than they needed to be. The updated comments have cleared up that issue as well with a shorter but more clear and direct explanations.

Changing the variable h and v to HE and VE respectively was a wise decision. While the original names would have been fine, the new names leave little doubt as to what they represent.

Since the changes made improve the readability of the code for future users and have not created any new issues, this commit is fine to merge with the main branch.

**Comment by jaykay99992** [comment]
@nrf-um Sure, I will merge it shortly. If you have any objections, please let me know :)

**Comment by nrf-um** [comment]
@jaykay99992 I have no objections. Go ahead and merge :)

**Comment by jaykay9999** [comment]
Sure, code approved and merged

**Pull request merged**
