### PR TITLE
removed repetitive comments

### PR DESCRIPTION
**Pull request by jaykay99992**
Removed repeated comments that explains the params m , app , v. Only kept the definitions for the first time they are declared.

I also removed the "mostly used" comments for each method and kept what it does , for code clarity.

### CODE REVIEW

**Review by Revanthjay — APPROVED** [review]
Hi jaykay,
You did a good job removing repetitive comments in between the code. This have improved the code maintainability and readability. Thanks.

**Comment by jaykay9999** [comment]
@Revanthjay Thank you for the remarks, Do I proceed to merge this new code ?

**Comment by Revanthjay** [comment]
@jaykay99992 Please proceed to merge. Thanks

**Comment by jaykay9999** [comment]
code approved and merged

**Pull request merged**
